[package]
name = "block_proof"
version = "0.1.0"
edition = "2021"

[workspace]


[dependencies]
risc0-zkvm = { version = "^2.0.2", default-features = false, features = ['std'] }
blockchain = { path = "../../blockchain" }
serde = "1.0"
serde_json = "1.0"
